### ISSUE TITLE
We need a branch that supports JDK 8 #1206

### ISSUE THREAD

**Issue by juna962** [gitlab4j/gitlab4j-api#1214] opened 2024-12-18 07:45 UTC
I noticed that the GitLab main branch has been upgraded to version 6.x, which requires JDK 11 or higher. Unfortunately, this is incompatible with the project. Could you create a branch that supports JDK 8?

**Comment by jmini** [comment] 2024-12-24 10:00
Duplicate of #1206

**Closed by jmini** 2024-12-24 10:00 UTC
