### ISSUE TITLE
JobApi class - JobId should be defined as Long

### ISSUE THREAD

**Issue by Bascil79** [gitlab4j/gitlab4j-api#819] opened 2022-03-14 06:36 UTC
The library failes to get jobs when the project Job Id is larger than max Integer  value.

**Comment by jabby** [comment] 2022-03-14 12:03
Duplicate of 809 and 810
Check https://github.com/gitlab4j/gitlab4j-api/issues/810 for updates. Fix will be released this week.

**Closed by jabby** 2022-03-14 12:03 UTC
