### ISSUE TITLE
Get commits for master branch

### ISSUE THREAD

**Issue by TamasNeumer** [gitlab4j/gitlab4j-api#440] opened 2019-09-27 12:42 UTC
Hi!

I ran into the following issue today:

- Your API has the following documentation:

```java
/**
     * Get a Pager of repository commits in a project.
     *
     * <pre><code>GitLab Endpoint: GET /projects/:id/repository/commits</code></pre>
     *
     * @param projectIdOrPath the project in the form of an Integer(ID), String(path), or Project instance
     * @param ref the name of a repository branch or tag or if not given the default branch
     * @param since only commits after or on this date will be returned
     * @param until only commits before or on this date will be returned
     * @param itemsPerPage the number of Commit instances that will be fetched per page
     * @return a Pager containing the commits for the specified project ID
     * @throws GitLabApiException GitLabApiException if any exception occurs during execution
     */
    public Pager<Commit> getCommits(Object projectIdOrPath, String ref, Date since, Date until, int itemsPerPage) throws GitLabApiException {
        return getCommits(projectIdOrPath, ref, since, until, null, itemsPerPage);
    }
```

- In my application I call the following function `gitLabApi.commitsApi.getCommits(repositoryName, "master", null, null, gitLabApi.defaultPerPage).all()`

- I was expecting to receive the commits only for the master branch, but I have received **all** the commits.

- Also when calling the `public List<Commit> getCommits(Object projectIdOrPath)`, it did NOT return all the commits. It returned 63 commits, (and I have 63 commits on my master branch according to the GitLab UI), but some commits were missing that (according the UI) were committed to the master branch. (So I assume I got a mixture of master/dev commits...)

- Looking up the GitLab API, the following should do the job: `https://gitlabUrl/api/v4/projects/11/repository/commits?ref_name=master` (+ Using pagination to get all commits.)

**Comment by gmessner** [comment] 2019-09-27 13:41
@TamasNeumer 
This library is making exactly the call that you specified in the final line when you pass null for the ```since``` and ```until``` params, the issue is that GitLab has changed the behavior and there are now 3 additional parameters that can be specified (see https://docs.gitlab.com/ce/api/commits.html#list-repository-commits):

Attribute | Type | Required | Description
-- | -- | -- | --
all | boolean | no | Retrieve every commit from the repository
with_stats | boolean | no | Stats about each commit will be added to the response
first_parent | boolean | no | Follow only the first parent commit upon seeing a merge commit

In the next release we will implement a method to make the call with these additional parameters but keep in mind, this library only calls the GitLab API it does not add any behavior, so if you believe the call is returning the wrong values, then there is a problem with the GitLab API, not this library.  This can be verified by using Postman to make the call and see what it returns.

**Comment by gmessner** [comment] 2019-09-30 00:55
@TamasNeumer 
4.12.8 has been released with the new methods that include the parameters identified above (all, with_stats, first_parent).

**Comment by TamasNeumer** [comment] 2019-09-30 06:33
@gmessner 

Thank you very much for your effort. I have played around with the original GitLabAPI via Postman and I couldn't retrieve **only** master branch commits. I believe this is a bug (or "feature") of the original API and not of this Java API. => Closing Issue.

Background:
`https://mygitlab.com/api/v4/projects/11/repository/commits?ref_name=master` still returned `development` branch commits. :-(

**Closed** 2019-09-30 06:33 UTC

**Comment by gmessner** [comment] 2019-09-30 07:05
@TamasNeumer 
Did you try calling it as follows?
```
https://mygitlab.com/api/v4/projects/11/repository/commits?ref_name=master&all=false&first_parent=true
```

Or via GitLab4J-API as follows?
```
gitLabApi.getCommitsApi().getCommits(repositoryName, "master", null, null, null, false, false, true);
```

**Comment by TamasNeumer** [comment] 2019-09-30 12:06
`https://mygitlab.com/api/v4/projects/11/repository/commits?ref_name=master&all=false&first_parent=true` also returned commits from the development branch in my case. Also it only returned 20 commits and not all of them...

**Comment by gmessner** [comment] 2019-09-30 17:41
@TamasNeumer 
20 is the default ```per_page```, all results from GitLab are paged, that is why you are seeing only the first 20.  You can get up to 100 per page as follows:
```
https://mygitlab.com/api/v4/projects/11/repository/commits?ref_name=master&all=false&first_parent=true&per_page=100
```
Is it possible the ```development``` branch was merged into ```master``` and the commits were not squashed?
