### ISSUE TITLE
api result to bean

### ISSUE THREAD

**Issue by darklish** [gitlab4j/gitlab4j-api#448] opened 2019-10-11 07:28 UTC
when i use the api gitLabApi.getCommitsApi().getCommit(**, **) to want to get one commit detail,
the api return json LOWER_CASE_WITH_UNDERSCORES, so the result properties is null, how to fix the problem

**Comment by gmessner** [comment] 2019-10-11 09:02
@darklish 
All results from the GitLab API are json with LOWER_CASE_WITH_UNDERSCORES and this library works correctly with that.  The ObjectMapper that is utilized is found in ```org.gitlab4j.api.utils.JacksonJson``` and is configured to properly deserialize the JSON.

Either you are not using the library correctly or for some reason, the proper ObjectMapper is not being used which is usually caused by using an old version of this library or the correct dependencies are not being used.

**Comment by darklish** [comment] 2019-10-11 10:17
my use version 4.8.10, then use api Project project = gitLabApi.getProjectApi().getProject(namespace, projectName) and get:
Caused by: com.alibaba.fastjson.JSONException: parse enum org.gitlab4j.api.models.AccessLevel error, value : 20

**Comment by darklish** [comment] 2019-10-11 13:57
That i want to say if the project have fastjson jar and jackson jar how to force the jersey use jacksonProvider and not fastjsonProvider

**Comment by gmessner** [comment] 2019-10-11 15:13
@darklish Take a look at my answer to this issue:
https://github.com/gitlab4j/gitlab4j-api/issues/266

Also, if possible you need to be using the current version of this library, it is difficult to be answering questions on a version that is almost 2 years old.

**Comment by darklish** [comment] 2019-10-12 05:53
OK, thanks, because it have to json provider ,and witch one will be use is uncertain， i think that is a Hidden problems，but thanks。

**Comment by gmessner** [comment] 2019-10-12 22:25
@darklish 
I have made mods to explicitly specify ```org.gitlab4j.api.util.JacksonJson``` as the ObjectMapper provider for this library and removed the ```@Provider``` annotation from it so it will not be automatically used anywhere else.  

This has been released as 4.12.12, could you verify that it is working for you, and if so close this issue?

**Comment by darklish** [comment] 2019-10-14 09:36
i close the issue first

**Comment by darklish** [comment] 2019-10-24 06:49
I changed to use 4.12.12, but MessageBodyFactory works contain FastJsonProvider.

**Comment by gmessner** [comment] 2019-10-25 03:59
@darklish 
I assume you are still having the deserialization issue with 4.12.12 ?

**Comment by gmessner** [comment] 2019-11-10 02:07
@darklish 
I have released 4.12.18 that should explicitly and reliably use the correct provider for this library.  If you could verify for me I would appreciate it.

**Comment by gmessner** [comment] 2019-11-28 18:40
@darklish 
I beleive this issue is now properly addressed so I am closing this issue.  It would be great if you could still validate that it is working.  If you do please let me know the results.

Thanks.

**Closed by gmessner** 2019-11-28 18:40 UTC
