### ISSUE TITLE
org.gitlab4j.api.GitLabApiException: 404 Commit Not Found

### ISSUE THREAD

**Issue by MiloshC** [gitlab4j/gitlab4j-api#467] opened 2019-11-06 09:19 UTC
Hi,
I am trying to open an already cloned repository with gitlab4j 

 RepositoryFile repositoryFile = gitLabApi.getRepositoryFileApi().getFile(744, currentRelativePath.toAbsolutePath().toString() + "\\milosh\\.git", "ref");

and when i run with these parameters i get  

org.gitlab4j.api.GitLabApiException: 404 Commit Not Found error

If i change the Id parameter to path to the project

 RepositoryFile repositoryFile = gitLabApi.getRepositoryFileApi().getFile(currentRelativePath.toAbsolutePath().toString() + "\\milosh", currentRelativePath.toAbsolutePath().toString() + "\\milosh\\.git", "ref");

 I get 
org.gitlab4j.api.GitLabApiException: 404 Project Not Found error

Please advice for a solution for the problem.

**Comment by gmessner** [comment] 2019-11-07 16:44
@MiloshC 
The problem is that the path to the file is relative to the root of the repo, not the file system.

The project path is also not relative to the filesystem, for example if I ```gmessner``` had a project called ```abc```, the project path would be ```gmessner/abc```


Additionally the ```.git``` directory is not a file that you can get, the ```.git``` directory is for internal use by git only.

**Comment by gmessner** [comment] 2019-11-08 16:04
@MiloshC 
Can this issue be closed, or do you need additional help?

**Comment by gmessner** [comment] 2019-11-10 01:08
@MiloshC 
I am closing this issue, if you are still having problems or have additional questions regarding this issue please feel fro to re-open it.

**Closed by gmessner** 2019-11-10 01:08 UTC
Labels: question
