### ISSUE TITLE
RepositoryFileApi.getLastCommitId is broken

### ISSUE THREAD

**Issue by nkiesel** [gitlab4j/gitlab4j-api#361] opened 2019-05-20 18:33 UTC
There is no real documentation about what it should return.  I assumed that when called with a file and a commit-id where that commit is the parent of another commit, it would return the child commit id.  I reality, it seems in most cases to return the same commit id.  I realize that it's a bit unclear what _should_ be returned once we have branches.  So perhaps this is not really possible to do w/o also specifying the branch.  But as it stands the current API seems useless.

I looked at the code and it simply takes the value of `response.getHeaderString("X-Gitlab-Last-Commit-Id")` so the problem might be a Gitlab problem.  But at least some documentation on what to expect here would be nice.

**Comment by gmessner** [comment] 2019-05-20 21:54
@nkiesel 
Remember that this library is simply a Java wrapper for communicating with the GitLab REST API, and they have very little documentation around this. You'll find what documentation is available here: 
https://docs.gitlab.com/ce/api/repository_files.html#get-file-from-repository

Look specifically at the section that talks about using **HEAD** to fetch just the available file info with no content.  All ```RepositoryFileApi.getFileInfo() does is wrap this call, if it is returning bad info then the problem is with GitLab, not this library.  I would suggest submitting an issue with GitLab and have them improve their side of the documentation, which could then be used to clarify this in GitLab4J.

BTW, as you know from #358, I have been discovering lots of issues with the GitLab documentation.  I am currently working on major documentation fixes related to the Discussions API and Webhooks documentation and will be submitting a PR to https://gitlab.com/gitlab-org/gitlab-ce, but this one I cannot fix for them as I have no idea what it is supposed to be returning.  Someone would need to dive deep into the GitLab-CE code to figure this one out, and I just do not have time to do so, is that something you could look into?

**Comment by nkiesel** [comment] 2019-05-22 00:18
I will take this up with gitlab directly.

**Comment by gmessner** [comment] 2019-05-22 00:25
@nkiesel 
I have looked a bit more into this and will be adding some documentation in the RepositoryFile and RepositoryFileApi of this library that explains a bit on what the information means.  Looking at doing a release on Thursday. 

Since I am working on a pull request with documentation fixes, I will include this same information in the Repository File API at GitLab-CE, they can decide whether to include it or not.

I've gone ahead and re-opened this issue, and will let you know when the release is available.

**Comment by gmessner** [comment] 2019-11-28 19:29
@nkiesel 
I just have not had the time to properly address the GitLab API documentation issues, since we have already addressed your issue I am going to close this.

**Closed by gmessner** 2019-11-28 19:29 UTC
