### ISSUE TITLE
ProtectedBranch contains allowForcePush, but cannot persist it

### ISSUE THREAD

**Issue by dpalic** [gitlab4j/gitlab4j-api#1071] opened 2023-12-18 07:36 UTC
With #1051 there was the forced_push flag added. So far so good, but I did not find any way how I can persist this feature?

I would have expected it here:
https://github.com/gitlab4j/gitlab4j-api/blob/f7441c791ad2ceb9151dc0c1410adc85d500dcf8/src/main/java/org/gitlab4j/api/ProtectedBranchesApi.java#L122
as one of the protectBranch* methods, but cannot find there

**Comment by jmini** [comment] 2023-12-20 17:26
I think this issue is a duplicate of #1019, but yes this addition make sense
(personally I am doing this call outside of the **gitlab4j** client right now).

**Comment by dpalic** [comment] 2023-12-25 15:34
would be great if you could pull and merge it into the next version. Or do you require any further changes from my side to accept the code?

**Closed** 2023-12-26 19:38 UTC
